force-app/main/default/objects/Member__c/Member__c.object-meta.xml
<CustomObject>
    <label>Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Member__c/fields/Back_Squat__c.field-meta.xml
<CustomField>
    <fullName>Back_Squat__c</fullName>
    <label>Back Squat</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Member__c/fields/Bench_Press__c.field-meta.xml
<CustomField>
    <fullName>Bench_Press__c</fullName>
    <label>Bench Press</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Member__c/fields/Deadlift__c.field-meta.xml
<CustomField>
    <fullName>Deadlift__c</fullName>
    <label>Deadlift</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Member__c/fields/Shoulder_Press__c.field-meta.xml
<CustomField>
    <fullName>Shoulder_Press__c</fullName>
    <label>Shoulder Press</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Member__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <label>Weight</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Score__c/Score__c.object-meta.xml
<CustomObject>
    <label>Score</label>
    <nameField>
        <label>Score Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Score__c/fields/Member__c.field-meta.xml
<CustomField>
    <fullName>Member__c</fullName>
    <label>Member</label>
    <referenceTo>Member__c</referenceTo>
    <relationshipLabel>Scores</relationshipLabel>
    <relationshipName>Scores</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Score__c/fields/Reps__c.field-meta.xml
<CustomField>
    <fullName>Reps__c</fullName>
    <label>Reps</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Score__c/fields/Strength_Reps__c.field-meta.xml
<CustomField>
    <fullName>Strength_Reps__c</fullName>
    <label>Strength Reps</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Score__c/fields/Strength_Type__c.field-meta.xml
<CustomField>
    <fullName>Strength_Type__c</fullName>
    <label>Strength Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Score__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <label>Weight</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Score__c/fields/Workout__c.field-meta.xml
<CustomField>
    <fullName>Workout__c</fullName>
    <label>Workout</label>
    <referenceTo>Workout__c</referenceTo>
    <relationshipLabel>Scores</relationshipLabel>
    <relationshipName>Scores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Score__c/fields/Workout_Date__c.field-meta.xml
<CustomField>
    <fullName>Workout_Date__c</fullName>
    <formula>Workout__r.Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Workout Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Workout__c/Workout__c.object-meta.xml
<CustomObject>
    <label>Workout</label>
    <nameField>
        <label>Workout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Workouts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Workout__c/fields/Strength__c.field-meta.xml
<CustomField>
    <fullName>Strength__c</fullName>
    <label>Strength</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Back Squat</fullName>
            </value>
            <value>
                <fullName>Deadlift</fullName>
            </value>
            <value>
                <fullName>Bench Press</fullName>
            </value>
            <value>
                <fullName>Shoulder Press</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ScoreTriggerUtility.cls
public with sharing class ScoreTriggerUtility {
  public static void createRelatedBenchmark(List<Score__c> scores) {
    Map<String, String> liftMap = new Map<String, String>{
      'Back Squat' => 'Back_Squat__c',
      'Deadlift' => 'Deadlift__c',
      'Bench Press' => 'Bench_Press__c',
      'Shoulder Press' => 'Shoulder_Press__c'
    };
    List<Member__c> members = new List<Member__c>();
    List<Id> memberIds = new List<Id>();
    Map<Id, Member__c> memberMap = new Map<Id, Member__c>();
    for (Score__c s : scores) {
      memberIds.add(s.Member__c);
    }
    for (AggregateResult a : [
      SELECT Member__r.Id, Max(Weight__c) MaxWeight, Strength_Type__c
      FROM Score__c
      WHERE
        Member__c IN :memberIds
        AND Strength_Reps__c = 1
        AND Workout_Date__c >= :Date.Today().addDays(-90)
      GROUP BY Strength_Type__c, Member__r.Id
    ]) {
      Member__c m = memberMap.containsKey(a.Id)
        ? memberMap.get(a.Id)
        : new Member__c(Id = a.Id);

      String liftField = liftMap.get((String) a.get('Strength_Type__c'));
      m.put(liftField, a.get('MaxWeight'));
      memberMap.put(a.id, m);
    }
    Map<Id, Score__c> relatedWorkoutMap = new Map<Id, Score__c>(
      [
        SELECT Id, Workout__r.Strength__c, Workout__r.Reps__c
        FROM Score__c
        WHERE Id IN :scores
      ]
    );
    for (Score__c s : scores) {
      Member__c member = memberMap.get(s.Member__c);
      Score__c relatedWorkoutInfo = relatedWorkoutMap.get(s.Id);
      String liftField = liftMap.get(relatedWorkoutInfo.Workout__r.Strength__c);
      Decimal reps = relatedWorkoutInfo.Workout__r.Reps__c;
      Decimal weight = member.get(liftField) != null
        ? (Decimal) member.get(liftField)
        : 0;
      if (s.Weight__c >= weight && reps == 1) {
        member.put(liftField, s.Weight__c);
        members.add(member);
      }
    }
    update members;
  }
}