force-app/main/default/objects/Member__c/Member__c.object-meta.xml
<CustomObject>
    <label>Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Member__c/fields/Fitness_Level__c.field-meta.xml
<CustomField>
    <fullName>Fitness_Level__c</fullName>
    <label>Fitness Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fitness_Level</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Member__c/fields/Issues__c.field-meta.xml
<CustomField>
    <fullName>Issues__c</fullName>
    <label>Issues</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Issues</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Member__c/fields/Training_Class__c.field-meta.xml
<CustomField>
    <fullName>Training_Class__c</fullName>
    <label>Training Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Training_Class</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Workout__c/Workout__c.object-meta.xml
<CustomObject>
    <label>Workout</label>
    <nameField>
        <label>Workout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Workouts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Workout__c/fields/Fitness_Level__c.field-meta.xml
<CustomField>
    <fullName>Fitness_Level__c</fullName>
    <label>Fitness Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Beginner</fullName>
            </value>
            <value>
                <fullName>Intermediate</fullName>
            </value>
            <value>
                <fullName>Elite</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Workout__c/fields/Issues__c.field-meta.xml
<CustomField>
    <fullName>Issues__c</fullName>
    <label>Issues</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Knee</fullName>
            </value>
            <value>
                <fullName>Shoulder</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Workout__c/fields/Workout_Description__c.field-meta.xml
<CustomField>
    <fullName>Workout_Description__c</fullName>
    <label>Workout Description</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/globalValueSets/Fitness_Level.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Beginner</fullName>
        <default>true</default>
        <label>Beginner</label>
    </customValue>
    <customValue>
        <fullName>Intermediate</fullName>
    </customValue>
    <customValue>
        <fullName>Advanced</fullName>
    </customValue>
    <customValue>
        <fullName>Elite</fullName>
    </customValue>
    <masterLabel>Fitness Level</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Issues.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Knee</fullName>
    </customValue>
    <customValue>
        <fullName>Shoulder</fullName>
    </customValue>
    <masterLabel>Issues</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Training_Class.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Basic</fullName>
        <default>true</default>
        <label>Basic</label>
    </customValue>
    <customValue>
        <fullName>Bodybuilding</fullName>
    </customValue>
    <customValue>
        <fullName>Cross-Training</fullName>
    </customValue>
    <masterLabel>Training Class</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/WorkoutDistributor.cls
/*
    Created by Simon Sawyer
    Sends daily Workouts to gym Members according to fitness level, training class, and health issues
*/
public class WorkoutDistributor implements Schedulable{

    public void execute(SchedulableContext context){
        List<Member__c> members = [SELECT Name, Email__c, Training_Class__c, Fitness_Level__c, Issues__c FROM Member__c WHERE Active__c = TRUE AND Email__c != NULL];
        List<Workout__c> workouts = [SELECT Training_Class__c, Fitness_Level__c, Issues__c, Workout_Description__c, Date__c FROM Workout__c WHERE Date__c = TODAY];
        EmailTemplate template = [SELECT Id, Subject from EmailTemplate where Name = 'Workout Template' LIMIT 1];
        Map<Member__c, Workout__c> assignments = new Map<Member__c, Workout__c>();
        List<Messaging.SingleEmailMessage> messages = new List<Messaging.SingleEmailMessage>();

        Workout__c w = new Workout__c();
        for(Member__c m : members){
            w = getProgram(m, workouts);
            assignments.put(m, w);
            messages.add(sendWorkout(w, m, template));
        }
        List<Messaging.SendEmailResult> results = Messaging.sendEmail(messages);
    }
    //Finds correct program for a given member
    static Workout__c getProgram(Member__c m, List<Workout__c> workouts){
        for(Workout__c w : workouts){
            if((w.Training_Class__c == m.Training_Class__c) && (w.Fitness_Level__c == m.Fitness_Level__c) && (w.Issues__c == m.Issues__c)){
                return w;
            }
        }
        return null;
    }
    //Generates message to send workout to a given member
    static Messaging.SingleEmailMessage sendWorkout(Workout__c w, Member__c m, EmailTemplate template){

        Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
        message.setTemplateId(template.id);
        message.setToAddresses(new String[]{m.Email__c});
        message.setHtmlBody(w.Workout_Description__c);

        return message;
    }
}