force-app/main/default/objects/Member__c/Member__c.object-meta.xml
<CustomObject>
    <label>Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Member__c/fields/Fitness_Level__c.field-meta.xml
<CustomField>
    <fullName>Fitness_Level__c</fullName>
    <label>Fitness Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fitness_Level</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Workout__c/Workout__c.object-meta.xml
<CustomObject>
    <label>Workout</label>
    <nameField>
        <label>Workout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Workouts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Workout__c/fields/Fitness_Level__c.field-meta.xml
<CustomField>
    <fullName>Fitness_Level__c</fullName>
    <label>Fitness Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Beginner</fullName>
            </value>
            <value>
                <fullName>Intermediate</fullName>
            </value>
            <value>
                <fullName>Elite</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Workout__c/fields/Workout_Description__c.field-meta.xml
<CustomField>
    <fullName>Workout_Description__c</fullName>
    <label>Workout Description</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/globalValueSets/Fitness_Level.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Beginner</fullName>
        <default>true</default>
        <label>Beginner</label>
    </customValue>
    <customValue>
        <fullName>Intermediate</fullName>
    </customValue>
    <customValue>
        <fullName>Advanced</fullName>
    </customValue>
    <customValue>
        <fullName>Elite</fullName>
    </customValue>
    <masterLabel>Fitness Level</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/WorkoutController.cls
public inherited sharing class WorkoutController {
    @AuraEnabled(cacheable=true)
    public static Workout__c getMemberWorkout(Id memberId,Date workoutDate){
        try {
            Member__c m = [Select Fitness_Level__c from Member__c Where Id=:memberId];
            return [SELECT Workout_Description__c,Fitness_Level__c
            FROM Workout__c 
            WHERE Fitness_Level__c =:m.Fitness_Level__c
            AND Date__c >: workoutDate.addDays(-1)
            AND Date__c <=: workoutDate
            LIMIT 1];
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
}