force-app/main/default/objects/Member__c/Member__c.object-meta.xml
<CustomObject>
    <label>Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Score__c/Score__c.object-meta.xml
<CustomObject>
    <label>Score</label>
    <nameField>
        <label>Score Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Score__c/fields/Member__c.field-meta.xml
<CustomField>
    <fullName>Member__c</fullName>
    <label>Member</label>
    <referenceTo>Member__c</referenceTo>
    <relationshipLabel>Scores</relationshipLabel>
    <relationshipName>Scores</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Score__c/fields/Workout__c.field-meta.xml
<CustomField>
    <fullName>Workout__c</fullName>
    <label>Workout</label>
    <referenceTo>Workout__c</referenceTo>
    <relationshipLabel>Scores</relationshipLabel>
    <relationshipName>Scores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Workout__c/Workout__c.object-meta.xml
<CustomObject>
    <label>Workout</label>
    <nameField>
        <label>Workout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Workouts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ScoreController.cls
public inherited sharing class ScoreController {
  @AuraEnabled(cacheable=true)
  public static Map<String, Id> getScoreRecordTypes() {
    try {
      List<RecordType> types = [
        SELECT Id, Name
        FROM RecordType
        WHERE SObjectType = 'Score__c'
      ];
      Map<String, Id> scoreMap = new Map<String, Id>();
      for (RecordType rt : types) {
        scoreMap.put(rt.Name, rt.Id);
      }
      return scoreMap;
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }
  @AuraEnabled(cacheable=true)
  public static Map<String, String> getScoresByMember(Id memberId) {
    try {
      Map<String, String> scoreMap = new Map<String, String>();
      List<Score__c> scores = [
        SELECT Id, Workout__c
        FROM Score__c
        WHERE Member__c = :memberId
      ];

      for (Score__c s : scores) {
        scoreMap.put((String) s.Workout__c, (String) s.Id);
      }
      System.debug(scoreMap);
      return scoreMap;
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }
}