force-app/main/default/objects/Member__c/Member__c.object-meta.xml
<CustomObject>
    <label>Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Member__c/fields/Fitness_Level__c.field-meta.xml
<CustomField>
    <fullName>Fitness_Level__c</fullName>
    <label>Fitness Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fitness_Level</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Member__c/fields/Training_Class__c.field-meta.xml
<CustomField>
    <fullName>Training_Class__c</fullName>
    <label>Training Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Training_Class</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Fitness_Level.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Beginner</fullName>
        <default>true</default>
        <label>Beginner</label>
    </customValue>
    <customValue>
        <fullName>Intermediate</fullName>
    </customValue>
    <customValue>
        <fullName>Advanced</fullName>
    </customValue>
    <customValue>
        <fullName>Elite</fullName>
    </customValue>
    <masterLabel>Fitness Level</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Training_Class.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Basic</fullName>
        <default>true</default>
        <label>Basic</label>
    </customValue>
    <customValue>
        <fullName>Bodybuilding</fullName>
    </customValue>
    <customValue>
        <fullName>Cross-Training</fullName>
    </customValue>
    <masterLabel>Training Class</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/MemberController.cls
/*
   Created by Kareem El Sayed
   a class to get the details of the members from the org to the Gym manager
*/
public inherited sharing class MemberController {
  /*
  @AuraEnabled(cacheable=true)
  public static List<Member__c> findMembers(String searchKey) {
    String key = '%' + searchKey + '%';
    return [
      SELECT Id, Name, Fitness_Level__c, Training_Class__c
      FROM Member__c
      WHERE Name LIKE :key
    ];
  }
  */
}