force-app/main/default/objects/Member__c/Member__c.object-meta.xml
<CustomObject>
    <label>Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Member__c/fields/BMI__c.field-meta.xml
<CustomField>
    <fullName>BMI__c</fullName>
    <label>BMI</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Member__c/fields/Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Birth__c</fullName>
    <label>Date of Birth</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Member__c/fields/Height_Feet__c.field-meta.xml
<CustomField>
    <fullName>Height_Feet__c</fullName>
    <label>Height (Feet)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Member__c/fields/Height_Inches__c.field-meta.xml
<CustomField>
    <fullName>Height_Inches__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Height (Inches)</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Member__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <label>Weight</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BMICalculatorLogicTest.cls
/*
   Created by Kareem El Sayed
   Test class to test if the BMI calculations are performed
*/
@isTest public inherited sharing class BMICalculatorLogicTest {
    @TestSetup
    static void makeData(){
       Member__c m = new Member__c(name = 'Tester', Date_of_Birth__c = Date.today(), Weight__c = 180, Height_Feet__c = 6, Height_Inches__c=5);
       insert m;
    }
    @isTest
    public static void performCalculations(){
        List<Member__c> member = [select name, BMI__c from Member__c where name like 'Tester' limit 1];
        if(member.size() > 0){
            System.assertEquals(21.344648525019768, member[0].BMI__c);
        }
    }
}