force-app/main/default/objects/Benchmark__c/Benchmark__c.object-meta.xml
<CustomObject>
    <label>Benchmark</label>
    <nameField>
        <label>Benchmark Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Benchmarks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Benchmark__c/fields/Back_Squat__c.field-meta.xml
<CustomField>
    <fullName>Back_Squat__c</fullName>
    <label>Back Squat</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Benchmark__c/fields/Bench_Press__c.field-meta.xml
<CustomField>
    <fullName>Bench_Press__c</fullName>
    <label>Bench Press</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Benchmark__c/fields/Deadlift__c.field-meta.xml
<CustomField>
    <fullName>Deadlift__c</fullName>
    <label>Deadlift</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Benchmark__c/fields/Goal_Benchmarks__c.field-meta.xml
<CustomField>
    <fullName>Goal_Benchmarks__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Goal Benchmarks</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Benchmark__c/fields/Member__c.field-meta.xml
<CustomField>
    <fullName>Member__c</fullName>
    <label>Member</label>
    <referenceTo>Member__c</referenceTo>
    <relationshipLabel>Benchmarks</relationshipLabel>
    <relationshipName>Benchmarks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Benchmark__c/fields/Shoulder_Press__c.field-meta.xml
<CustomField>
    <fullName>Shoulder_Press__c</fullName>
    <label>Shoulder Press</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Benchmark__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <label>Weight</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Member__c/Member__c.object-meta.xml
<CustomObject>
    <label>Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Member__c/fields/Back_Squat__c.field-meta.xml
<CustomField>
    <fullName>Back_Squat__c</fullName>
    <label>Back Squat</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Member__c/fields/Bench_Press__c.field-meta.xml
<CustomField>
    <fullName>Bench_Press__c</fullName>
    <label>Bench Press</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Member__c/fields/Current_Benchmark__c.field-meta.xml
<CustomField>
    <fullName>Current_Benchmark__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Benchmark</label>
    <referenceTo>Benchmark__c</referenceTo>
    <relationshipLabel>Members</relationshipLabel>
    <relationshipName>Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Member__c/fields/Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Birth__c</fullName>
    <label>Date of Birth</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Member__c/fields/Deadlift__c.field-meta.xml
<CustomField>
    <fullName>Deadlift__c</fullName>
    <label>Deadlift</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Member__c/fields/Goal_Benchmark__c.field-meta.xml
<CustomField>
    <fullName>Goal_Benchmark__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Goal Benchmark</label>
    <referenceTo>Benchmark__c</referenceTo>
    <relationshipLabel>Members (Goal Benchmark)</relationshipLabel>
    <relationshipName>Members1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Member__c/fields/Height_Feet__c.field-meta.xml
<CustomField>
    <fullName>Height_Feet__c</fullName>
    <label>Height (Feet)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Member__c/fields/Height_Inches__c.field-meta.xml
<CustomField>
    <fullName>Height_Inches__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Height (Inches)</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Member__c/fields/Shoulder_Press__c.field-meta.xml
<CustomField>
    <fullName>Shoulder_Press__c</fullName>
    <label>Shoulder Press</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Member__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <label>Weight</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BenchmarkTriggerUtilityTest.cls
@isTest
public inherited sharing class BenchmarkTriggerUtilityTest {
    @TestSetup
    static void makeData(){
        insert new Member__c(Name='Test Member',Height_Feet__c=5,Height_Inches__c=6,Date_of_Birth__c = Date.newInstance(1980, 3, 1));
        Id id = [Select Id from Member__c where Name ='Test Member'].Id;
        insert new Benchmark__c(Name='Goal Benchmark',
            Deadlift__c = 400,
            Bench_Press__c = 250,
            Shoulder_Press__c = 175,
            Back_Squat__c =350,
            Weight__c = 165,
            Member__c = id,
            Goal_Benchmarks__c = true);
        insert new Benchmark__c(Name='March Benchmark',
            Date__c = Date.newInstance(2021,3,1),
            Deadlift__c = 400,
            Bench_Press__c = 250,
            Shoulder_Press__c = 175,
            Back_Squat__c =350,
            Weight__c = 165,
            Member__c = id);
        insert new Benchmark__c(Name='February Benchmark',
            Date__c = Date.newInstance(2021,2,1),
            Deadlift__c = 400,
            Bench_Press__c = 250,
            Shoulder_Press__c = 175,
            Back_Squat__c =350,
            Weight__c = 165,
            Member__c = id);
    }
    @isTest
    static void isGoalBenchmarkTest(){
        Member__c m = [Select Goal_Benchmark__c from Member__c where Name ='Test Member'];
        Benchmark__c b = [Select Id from Benchmark__c where Name='Goal Benchmark'];
        System.assertEquals(m.Goal_Benchmark__c,b.Id);
    }
    @isTest 
    static void isCurrentBenchmarkTest(){
        Member__c m = [Select Current_Benchmark__c from Member__c where Name ='Test Member'];
        Benchmark__c b = [Select Id from Benchmark__c where Name='March Benchmark'];
        System.assertEquals(m.Current_Benchmark__c,b.Id);
    }
    @isTest
    static void isNotCurrentBenchmarkTest(){
        Member__c m = [Select Current_Benchmark__c from Member__c where Name ='Test Member'];
        Benchmark__c b = [Select Id from Benchmark__c where Name='February Benchmark'];
        System.assert(m.Current_Benchmark__c != b.Id);
    }
}