force-app/main/default/objects/Benchmark__c/Benchmark__c.object-meta.xml
<CustomObject>
    <label>Benchmark</label>
    <nameField>
        <label>Benchmark Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Benchmarks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Benchmark__c/fields/Back_Squat__c.field-meta.xml
<CustomField>
    <fullName>Back_Squat__c</fullName>
    <label>Back Squat</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Benchmark__c/fields/Bench_Press__c.field-meta.xml
<CustomField>
    <fullName>Bench_Press__c</fullName>
    <label>Bench Press</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Benchmark__c/fields/BMI__c.field-meta.xml
<CustomField>
    <fullName>BMI__c</fullName>
    <label>BMI</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Benchmark__c/fields/Deadlift__c.field-meta.xml
<CustomField>
    <fullName>Deadlift__c</fullName>
    <label>Deadlift</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Benchmark__c/fields/Fitness_Level__c.field-meta.xml
<CustomField>
    <fullName>Fitness_Level__c</fullName>
    <label>Fitness_Level</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Benchmark__c/fields/Goal_Benchmarks__c.field-meta.xml
<CustomField>
    <fullName>Goal_Benchmarks__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Goal Benchmarks</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Benchmark__c/fields/Member__c.field-meta.xml
<CustomField>
    <fullName>Member__c</fullName>
    <label>Member</label>
    <referenceTo>Member__c</referenceTo>
    <relationshipLabel>Benchmarks</relationshipLabel>
    <relationshipName>Benchmarks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Benchmark__c/fields/Shoulder_Press__c.field-meta.xml
<CustomField>
    <fullName>Shoulder_Press__c</fullName>
    <label>Shoulder Press</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Benchmark__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <label>Weight</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Member__c/Member__c.object-meta.xml
<CustomObject>
    <label>Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Member__c/fields/Back_Squat__c.field-meta.xml
<CustomField>
    <fullName>Back_Squat__c</fullName>
    <label>Back Squat</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Member__c/fields/Bench_Press__c.field-meta.xml
<CustomField>
    <fullName>Bench_Press__c</fullName>
    <label>Bench Press</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Member__c/fields/BMI__c.field-meta.xml
<CustomField>
    <fullName>BMI__c</fullName>
    <label>BMI</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Member__c/fields/Current_Benchmark__c.field-meta.xml
<CustomField>
    <fullName>Current_Benchmark__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Benchmark</label>
    <referenceTo>Benchmark__c</referenceTo>
    <relationshipLabel>Members</relationshipLabel>
    <relationshipName>Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Member__c/fields/Deadlift__c.field-meta.xml
<CustomField>
    <fullName>Deadlift__c</fullName>
    <label>Deadlift</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Member__c/fields/Fitness_Level__c.field-meta.xml
<CustomField>
    <fullName>Fitness_Level__c</fullName>
    <label>Fitness Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fitness_Level</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Member__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Member__c/fields/Goal_Benchmark__c.field-meta.xml
<CustomField>
    <fullName>Goal_Benchmark__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Goal Benchmark</label>
    <referenceTo>Benchmark__c</referenceTo>
    <relationshipLabel>Members (Goal Benchmark)</relationshipLabel>
    <relationshipName>Members1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Member__c/fields/Height_Feet__c.field-meta.xml
<CustomField>
    <fullName>Height_Feet__c</fullName>
    <label>Height (Feet)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Member__c/fields/Height_Inches__c.field-meta.xml
<CustomField>
    <fullName>Height_Inches__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Height (Inches)</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Member__c/fields/Shoulder_Press__c.field-meta.xml
<CustomField>
    <fullName>Shoulder_Press__c</fullName>
    <label>Shoulder Press</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Member__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <label>Weight</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Fitness_Level.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Beginner</fullName>
        <default>true</default>
        <label>Beginner</label>
    </customValue>
    <customValue>
        <fullName>Intermediate</fullName>
    </customValue>
    <customValue>
        <fullName>Advanced</fullName>
    </customValue>
    <customValue>
        <fullName>Elite</fullName>
    </customValue>
    <masterLabel>Fitness Level</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BenchmarkTriggerUtility.cls
public inherited sharing class BenchmarkTriggerUtility {
    public static void setBenchmarkEmptyFields(List<Benchmark__c> bens){
        for(Benchmark__c b:bens){
            try{
                b.Date__c = b.Date__c == null ? Date.Today() : b.Date__c;
                List<Benchmark__c> mRecent = [SELECT Deadlift__c,Back_Squat__c,Bench_Press__c,Shoulder_Press__c,Weight__c FROM Benchmark__c 
                                    WHERE Date__c <: b.Date__c AND Member__c =: b.Member__c AND Goal_Benchmarks__c=false
                                    ORDER BY Date__c DESC
                                    LIMIT 1];
                if(mRecent.size() != 0) {
                    b.Deadlift__c = b.Deadlift__c == null ? mRecent[0].Deadlift__c:b.Deadlift__c;
                    b.Back_Squat__c = b.Back_Squat__c == null ? mRecent[0].Back_Squat__c:b.Back_Squat__c;
                    b.Bench_Press__c = b.Bench_Press__c == null ? mRecent[0].Bench_Press__c:b.Bench_Press__c;
                    b.Shoulder_Press__c = b.Shoulder_Press__c == null ? mRecent[0].Shoulder_Press__c:b.Shoulder_Press__c;
                    b.Weight__c = b.Weight__c == null ? mRecent[0].Weight__c : b.weight__c;
                }
               
            } catch (QueryException e) {
                throw new AuraHandledException(e.getMessage());
            }
        
        }
    }
    
    public static void fitnessLevel(List<Benchmark__c> bens){
        List<Member__c> members = [SELECT Id, Weight__c, Gender__c FROM Member__c WHERE Active__c = TRUE];
        Map<Benchmark__c, Member__c> bmMap = new Map<Benchmark__c, Member__c>();
        for(Benchmark__c b : bens){
            for(Member__c m : members){
                if(b.Member__c == m.Id){
                    bmMap.put(b, m);
                }
            }
        }
        for (Benchmark__c b:bens){
            b.Fitness_Level__c = LiftStandardsController.getFitnessLevel(b, bmMap.get(b));
        }
    }
    public static void BMICalculator(List<Benchmark__c> bens){
        for(Benchmark__c b:bens){
            if(b.Weight__c != null){
                Member__c m = [Select Height_Feet__c,Height_Inches__c from Member__c where Id=:b.Member__c];
                if(m.Height_Feet__c != null && m.Height_Inches__c != null){
                    Double weightInKilos = b.Weight__c * 0.453592;
                    Double heightInMeters = (((m.Height_Feet__c * 12) + m.Height_Inches__c)* .0254);
                    Double bmi = weightInKilos / (heightInMeters * heightInMeters);
                    b.BMI__c = bmi; 
                }
            }
        }
        
    }
    public static void isGoalBenchmark(List<Benchmark__c> bens) {
        for(Benchmark__c b:bens){
            if(b.Goal_Benchmarks__c){
                Member__c m = [Select Id from Member__c Where Id=:b.Member__c];
                //m.Goal_Benchmark__c = b.Id;
                update m;
            }
        }
    }
    public static void isCurrentBenchmark(List<Benchmark__c> bens) {
        for(Benchmark__c b:bens){
            if(b.Date__c >= Date.Today().toStartofMonth() && b.Date__c < Date.Today().addMonths(1).toStartofMonth()){
                Member__c m = [Select Id from Member__c Where Id=:b.Member__c];
                //m.Current_Benchmark__c = b.Id;
                m.Fitness_Level__c = b.Fitness_Level__c;
                m.BMI__c = b.BMI__c;
                update m;
            }
        }
    }
    
         
    
    
}